version: "3.8"
   
services:
    django:
        build: .
        container_name: django
        command: python manage.py wait_for_db &&
                 python manage.py migrate 
                 python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/app
        ports:
            - "8000:8000"
        environment:
          - DB_HOST=db
          - DB_NAME=appdb
          - DB_USER=postgres
          - DB_PASS=supersecretpassword    
        depends_on:
            - db
    db:
        image: postgres:11-alpine
        environment:
        - POSTGRES_DB=core
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=supersecretpassword   